#!/bin/bash

#the script counts your last day gmail unread emails. If it doesn't work, check your email account 

USER=#Your_Gmail_Username
PASS=#Your_Password
USER1=#Your_Gmail_Username
PASS1=#Your_Password
 
COUNT=`curl -su $USER:$PASS https://mail.google.com/mail/feed/atom || echo "<fullcount>unknown number of</fullcount>"`
COUNT=`echo "$COUNT" | grep -oPm1 "(?<=<fullcount>)[^<]+"`

COUNT1=`curl -su $USER1:$PASS1 https://mail.google.com/mail/feed/atom || echo "<fullcount>unknown number of</fullcount>"`
COUNT1=`echo "$COUNT1" | grep -oPm1 "(?<=<fullcount>)[^<]+"`

if [ "$COUNT" != "0" ] && [ "$COUNT1" != "0" ]; then
    echo "  P:$COUNT W:$COUNT1"
    else
    if [ "$COUNT" != "0" ]; then9d
       echo "  P:$COUNT"
       else 
        if [ "$COUNT1" != "0" ]; then
            echo "  W:$COUNT1"
        fi
    fi
fi

